### PR TITLE
navigation: Fix navigation header for the main website

### PR DESCRIPTION
**Pull request by vanshika0109**
**What does this PR do?**

In minimize or tablet screen:
image

For mobile phone (specifically, iPhone X) screen:
image

For these two screen the it fixes the navigation behaviour and adds the
menu button on requirement to remove cluttering.

### CODE REVIEW

**Comment by j143** [comment]
Are you sure just for navigation bar we have this much of the css. Please try to work with the
existing code and slightly modify that code.

**Comment by j143** [comment]
BTW, the navigation code for main header stay at `_src/_sass/_navigation.scss` file.
https://github.com/j143/systemds-website/blob/7c9284a4655f25cc78dc8ab390f58292c927afbb/_src/_sass/_navigation.scss#L2

**About `.scss`** (1 min read)

> image

And `.scss` will be compiled to `.css`. 

** What? 😕 ** (3 min read)

1. The `main.scss` file 
image
is changed.
2. During `gulp` command it is compiled to `main.css` (the code that you have provided, I guess)

**Comment by vanshika0109** [comment]
Sure, I would work on the code.😊

**Comment by j143** [comment]
providing update as early as you can helps the development faster. Let's sure each `iteration` is no more than `6 hours`.

**1. What is iteration?** (~1 min read)
> Do a small change which would show the functionality -> an iteration
> With each iteration increase the complexity of the code.
> After each iteration ask for review.

**2. How approach the work on quality code?** (~ 2 min read)
(A snippet from the first `work-update`:)

image

Thank you.

**Comment by j143** [comment]
@vanshika0109 
To change styles, we need to edit https://github.com/j143/systemds-website/blob/master/_src/_sass/_navigation.scss

https://github.com/j143/systemds-website/pull/7#issuecomment-659993708 explains how this works.

NOTE: We  are not talking about `main.css` (which is generated!) file.

**Comment by j143** [comment]
Any updates?

**Comment by j143** [comment]
Hi @vanshika0109 - If you are finding changing styles to be difficult. Feel free to schedule a meet. :smile:

**Comment by vanshika0109** [comment]
> Any updates?

Not yet, but I am still trying to minimise the code.

**Comment by vanshika0109** [comment]
According to me, the code can be minimised for a few lines only since for the proper functionality of the navigation bar we need all the CSS. How should I share the minimised code to you @j143?

**Comment by j143** [comment]
Hi @vanshika0109 - It is very important that you make small changes

Step 1. Fix or add functionality (something that is working) (take a deep breath, ~3 min read, and :smile:)
  - [ ] If you have implemented navigation copy/paste the visual screen shot
  - [ ] just use the below options in dev tools, to create interactivity after that you can
use js or css to create click functionality.
  
image


Step 2. Optimize the code or minimize or optimize.

These steps are to make sure your work is going in the direction the team is intending.

Engineers should not believe in miracles, engineering is a miracle!

**Comment by j143** [comment]
Hey @vanshika0109 try to update this PR, with code and Screeshots.

**Comment by vanshika0109** [comment]
> Hey @vanshika0109 try to update this PR, with code and Screenshots.

Okay!

**Pull request closed without merging**
